# Generated by Django 5.1.2 on 2024-12-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', 'XXXX_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('timezone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaAdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('targeting', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_optimization', models.BooleanField(default=True)),
                ('objective', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='meta.metaadaccount')),
            ],
        ),
        migrations.CreateModel(
            name='MetaPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('ctr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MetaAdSpend',
        ),
        migrations.AddField(
            model_name='metaadset',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='meta.metacampaign'),
        ),
        migrations.AddField(
            model_name='metaadaccount',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accounts', to='meta.metaportfolio'),
        ),
        migrations.AddField(
            model_name='metaspend',
            name='adset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_records', to='meta.metaadset'),
        ),
        migrations.AddField(
            model_name='metaspend',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_records', to='meta.metacampaign'),
        ),
        migrations.AddIndex(
            model_name='metaspend',
            index=models.Index(fields=['date'], name='meta_metasp_date_cf5a00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metaspend',
            unique_together={('date', 'campaign', 'adset')},
        ),
    ]
