# Generated by Django 5.1.2 on 2024-11-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField()),
                ('tags', models.JSONField(default=list)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='shopify_sho_name_12aa57_idx'), models.Index(fields=['created_at'], name='shopify_sho_created_02d106_idx')],
            },
        ),
    ]
