# Generated by Django 5.1.2 on 2024-11-30 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayOAuthCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100)),
                ('dev_id', models.CharField(max_length=100)),
                ('cert_id', models.CharField(max_length=100)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Ebay OAuth Credentials',
            },
        ),
        migrations.CreateModel(
            name='EbayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('order_status', models.CharField(max_length=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('payment_status', models.CharField(max_length=50)),
                ('shopify_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebay_orders', to='shopify.shopifyorder')),
            ],
        ),
        migrations.CreateModel(
            name='EbayOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('seller_id', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ebay.ebayorder')),
            ],
        ),
        migrations.AddIndex(
            model_name='ebayorder',
            index=models.Index(fields=['order_id'], name='ebay_ebayor_order_i_03ea79_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayorder',
            index=models.Index(fields=['created_at'], name='ebay_ebayor_created_3acaa1_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayorder',
            index=models.Index(fields=['shopify_order'], name='ebay_ebayor_shopify_4a2c28_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayorderitem',
            index=models.Index(fields=['item_id'], name='ebay_ebayor_item_id_c6e76c_idx'),
        ),
        migrations.AddIndex(
            model_name='ebayorderitem',
            index=models.Index(fields=['seller_id'], name='ebay_ebayor_seller__ac20f2_idx'),
        ),
    ]
