# Generated by Django 5.1.2 on 2024-12-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_ebayorderitem_actual_shipping_cost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EbayOAuthCredentials',
        ),
    ]
